// Scout setup: private directories, mode-exact writes, the wrapper script, and marker checks.

import { chmodSync, lstatSync, mkdirSync, readFileSync, renameSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join, basename } from "node:path";

export const WRAPPER_MARKER_PREFIX = "# scout-marker: ";

/** Double-quote a string for /bin/sh. */
export function shDoubleQuote(s) {
  if (typeof s !== "string" || /[\0\n]/.test(s)) throw new Error(`cannot quote path: ${JSON.stringify(s)}`);
  return `"${s.replace(/[\\"$`]/g, "\\$&")}"`;
}

/** The native host wrapper Chrome launches. SCOUT_HOME is pinned so the host reads the same config setup wrote. */
export function wrapperScript({ nodePath, hostJs, scoutHome, marker }) {
  return `#!/bin/sh
${WRAPPER_MARKER_PREFIX}${marker}
# Generated by scout/scripts/setup.mjs. Chrome runs this with the caller origin as $1.
SCOUT_HOME=${shDoubleQuote(scoutHome)}
export SCOUT_HOME
exec ${shDoubleQuote(nodePath)} ${shDoubleQuote(hostJs)} "$@"
`;
}

/**
 * Check `dir` without changing anything. Throws on a symlink, a non-directory, or a
 * directory owned by someone else. Returns { exists, mode } (mode null when absent).
 */
export function checkPrivateDir(dir) {
  let st;
  try {
    st = lstatSync(dir);
  } catch (e) {
    if (e.code === "ENOENT") return { exists: false, mode: null };
    throw e;
  }
  if (st.isSymbolicLink() || !st.isDirectory()) throw new Error(`${dir} is not a directory`);
  if (st.uid !== process.getuid()) throw new Error(`${dir} is not owned by the current user`);
  return { exists: true, mode: st.mode & 0o777 };
}

/** Create `dir` (and parents) and force it to 0700. Refuses a symlink, non-directory, or foreign owner. */
export function ensurePrivateDir(dir) {
  checkPrivateDir(dir);
  mkdirSync(dir, { recursive: true, mode: 0o700 });
  const { mode } = checkPrivateDir(dir);
  if (mode !== 0o700) chmodSync(dir, 0o700);
}

/** Write via a fresh temp file + rename, with an exact mode. A stale temp file is removed first. */
export function writeFileMode(path, content, mode) {
  const tmp = join(dirname(path), `.${basename(path)}.${process.pid}.tmp`);
  try {
    unlinkSync(tmp);
  } catch (e) {
    if (e.code !== "ENOENT") throw e;
  }
  writeFileSync(tmp, content, { mode, flag: "wx" });
  chmodSync(tmp, mode);
  renameSync(tmp, path);
}

export function writeJson(path, value, mode) {
  writeFileMode(path, JSON.stringify(value, null, 2) + "\n", mode);
}

/** Parsed JSON object, null if the file is absent. Throws if present but not a JSON object. */
export function readJsonObject(path) {
  let text;
  try {
    text = readFileSync(path, "utf8");
  } catch (err) {
    if (err.code === "ENOENT") return null;
    throw err;
  }
  const v = JSON.parse(text);
  if (v === null || typeof v !== "object" || Array.isArray(v)) throw new Error(`${path} is not a JSON object`);
  return v;
}

/** The Scout marker a file carries (JSON `x_scout_marker` or wrapper comment line), or null. */
export function fileMarker(path, kind) {
  let text;
  try {
    text = readFileSync(path, "utf8");
  } catch {
    return null;
  }
  if (kind === "wrapper") {
    const line = text.split("\n").find((l) => l.startsWith(WRAPPER_MARKER_PREFIX));
    return line ? line.slice(WRAPPER_MARKER_PREFIX.length).trim() : null;
  }
  try {
    const v = JSON.parse(text);
    return typeof v?.x_scout_marker === "string" ? v.x_scout_marker : null;
  } catch {
    return null;
  }
}

export function exists(path) {
  try {
    lstatSync(path);
    return true;
  } catch {
    return false;
  }
}
