// Scout Phase 0 bridge spike: generate the native-host wrapper and manifest.
//
// Writes only inside `outDir` (and creates the private `runtimeDir`). Never
// touches Chrome's Library folders or any profile. The generated install /
// uninstall scripts are for Hunter to run by hand; nothing here runs them.

import { chmodSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, join } from "node:path";
import { fileURLToPath } from "node:url";
import { HOST_NAME, ORIGIN_RE } from "./native-host.mjs";
import { ensurePrivateRuntimeDir } from "./runtime-dir.mjs";

export const HOST_SCRIPT = join(dirname(fileURLToPath(import.meta.url)), "native-host.mjs");
export const REAL_CHROME_HOSTS_DIR_EXPR = '"$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts"';

/** POSIX single-quote a string for /bin/sh. */
export function shQuote(s) {
  if (typeof s !== "string" || s.includes("\0") || s.includes("\n")) throw new Error("unquotable");
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

export function wrapperScript({ runtimeDir, origin, nodePath, hostScript }) {
  return `#!/bin/sh
# Generated by scout/scripts/spikes/bridge/prepare-host.mjs. Phase 0 spike only.
# Chrome runs this with the caller origin as $1; the host checks it exactly.
cd -- ${shQuote(runtimeDir)} || exit 1
SCOUT_BRIDGE_ALLOWED_ORIGIN=${shQuote(origin)}
export SCOUT_BRIDGE_ALLOWED_ORIGIN
exec ${shQuote(nodePath)} ${shQuote(hostScript)} "$@"
`;
}

export function hostManifest({ wrapperPath, origin }) {
  return {
    name: HOST_NAME,
    description: "Scout Phase 0 bridge spike (throwaway)",
    path: wrapperPath,
    type: "stdio",
    allowed_origins: [origin],
  };
}

function installScripts(manifestPath) {
  const target = `${REAL_CHROME_HOSTS_DIR_EXPR}/${HOST_NAME}.json`;
  const install = `#!/bin/sh
# Manual step for Hunter. Registers the Scout spike native host with the
# REAL Chrome profile by copying one manifest file. Nothing runs this for you.
set -eu
DIR=${REAL_CHROME_HOSTS_DIR_EXPR}
TARGET=${target}
if [ -e "$TARGET" ] && ! cmp -s ${shQuote(manifestPath)} "$TARGET"; then
  echo "refusing: a different $TARGET already exists" >&2
  exit 1
fi
mkdir -p "$DIR"
cp ${shQuote(manifestPath)} "$TARGET"
echo "installed $TARGET"
`;
  const uninstall = `#!/bin/sh
# Manual step for Hunter. Removes the Scout spike native host manifest, only
# if it is exactly the one this prepare run generated.
set -eu
TARGET=${target}
if [ ! -e "$TARGET" ]; then echo "not installed"; exit 0; fi
if ! cmp -s ${shQuote(manifestPath)} "$TARGET"; then
  echo "refusing: $TARGET differs from the prepared manifest" >&2
  exit 1
fi
rm -- "$TARGET"
echo "removed $TARGET"
`;
  return { install, uninstall };
}

/**
 * Generate wrapper, host manifest and manual install/uninstall scripts under
 * `outDir/native-host/`. Returns their absolute paths.
 */
export function prepareNativeHost({ outDir, runtimeDir, extensionId, nodePath = process.execPath, hostScript = HOST_SCRIPT }) {
  for (const p of [outDir, runtimeDir, nodePath, hostScript]) if (!isAbsolute(p)) throw new Error("absolute paths required");
  const origin = `chrome-extension://${extensionId}/`;
  if (!ORIGIN_RE.test(origin)) throw new Error("bad extension id");
  ensurePrivateRuntimeDir(runtimeDir);
  const dir = join(outDir, "native-host");
  mkdirSync(dir, { recursive: true });
  const wrapperPath = join(dir, "scout-spike-bridge-host.sh");
  writeFileSync(wrapperPath, wrapperScript({ runtimeDir, origin, nodePath, hostScript }));
  chmodSync(wrapperPath, 0o755);
  const manifestPath = join(dir, `${HOST_NAME}.json`);
  writeFileSync(manifestPath, JSON.stringify(hostManifest({ wrapperPath, origin }), null, 2) + "\n");
  const { install, uninstall } = installScripts(manifestPath);
  const installPath = join(dir, "install-real-chrome.sh");
  const uninstallPath = join(dir, "uninstall-real-chrome.sh");
  writeFileSync(installPath, install);
  writeFileSync(uninstallPath, uninstall);
  chmodSync(installPath, 0o755);
  chmodSync(uninstallPath, 0o755);
  return { dir, wrapperPath, manifestPath, installPath, uninstallPath, origin, runtimeDir };
}
