#!/usr/bin/env node
// Scout Phase 0 GitHub capture spike: package the throwaway extension and the
// native-host artifacts.
//
//   node prepare.mjs --out <absolute dir> [--runtime-dir <absolute dir>]
//                    [--isolated-profile <absolute dir>]
//
// Writes ONLY under --out (plus the private runtime dir and, if asked, a
// throwaway isolated browser profile dir). Never writes to Chrome's Library
// folders or to a real profile; the real-Chrome install script it generates is
// for Hunter to run by hand. Prints a JSON summary of paths and the stable
// extension id (derived from a generated public key, kept in --out so the id
// survives re-runs). No private key is written.

import { createHash, generateKeyPairSync } from "node:crypto";
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, isAbsolute, join, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { isMain } from "../bridge/is-main.mjs";
import { prepareNativeHost } from "../bridge/prepare-host.mjs";
import { buildManifest } from "./src/manifest.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = join(HERE, "src");
const BRIDGE = join(HERE, "..", "bridge");
export const CONTENT_BUNDLE_SOURCES = ["route.mjs", "selectors.mjs", "content-core.mjs"];
const COPY = ["background.js", "background-core.mjs", "route.mjs", "selectors.mjs", "popup.html", "popup.mjs", "popup-view.mjs"];

export function extensionIdFromKey(publicKeyDerB64) {
  const hex = createHash("sha256").update(Buffer.from(publicKeyDerB64, "base64")).digest("hex").slice(0, 32);
  return [...hex].map((c) => String.fromCharCode(97 + parseInt(c, 16))).join("");
}

export function generatePublicKey() {
  const { publicKey } = generateKeyPairSync("rsa", { modulusLength: 2048 });
  return publicKey.export({ type: "spki", format: "der" }).toString("base64");
}

/**
 * Concatenate the dependency-free content modules into one classic IIFE
 * script. Each source may only use top-level `import ... from "./x.mjs";` of
 * other bundled files and `export` declarations.
 */
export function bundleContentScript(srcDir = SRC) {
  const parts = CONTENT_BUNDLE_SOURCES.map((f) => {
    const text = readFileSync(join(srcDir, f), "utf8");
    const out = text
      .split("\n")
      .filter((line) => {
        if (!/^import\s/.test(line)) return true;
        const m = line.match(/from\s+"\.\/([^"]+)";\s*$/);
        if (!m || !CONTENT_BUNDLE_SOURCES.includes(m[1])) throw new Error(`unbundleable import in ${f}`);
        return false;
      })
      .map((line) => line.replace(/^export\s+(?=(const|function|class|let|async)\b)/, ""))
      .join("\n");
    if (/^\s*(import|export)\b/m.test(out)) throw new Error(`leftover module syntax in ${f}`);
    return `// ---- ${f} ----\n${out}`;
  });
  return `// Generated by prepare.mjs from ${CONTENT_BUNDLE_SOURCES.join(", ")}. Do not edit.\n(() => {\n"use strict";\n${parts.join("\n")}\nstartContentScript(chrome, window);\n})();\n`;
}

function refuseRealChromeDirs(p) {
  const lib = join(homedir(), "Library") + sep;
  if ((resolve(p) + sep).startsWith(lib)) throw new Error("refusing to write under ~/Library");
}

export function prepare({ out, runtimeDir = join(out, "runtime"), isolatedProfile = null }) {
  for (const p of [out, runtimeDir, ...(isolatedProfile ? [isolatedProfile] : [])]) {
    if (!isAbsolute(p)) throw new Error("absolute paths required");
    refuseRealChromeDirs(p);
  }
  mkdirSync(out, { recursive: true });
  const keyFile = join(out, "extension-public-key.json");
  let key;
  if (existsSync(keyFile)) key = JSON.parse(readFileSync(keyFile, "utf8")).publicKeyDerB64;
  else {
    key = generatePublicKey();
    writeFileSync(keyFile, JSON.stringify({ publicKeyDerB64: key }, null, 2) + "\n");
  }
  const extensionId = extensionIdFromKey(key);

  const ext = join(out, "extension");
  mkdirSync(ext, { recursive: true });
  writeFileSync(join(ext, "manifest.json"), JSON.stringify(buildManifest({ key }), null, 2) + "\n");
  for (const f of COPY) copyFileSync(join(SRC, f), join(ext, f));
  copyFileSync(join(BRIDGE, "reconnect-policy.mjs"), join(ext, "reconnect-policy.mjs"));
  writeFileSync(join(ext, "content.js"), bundleContentScript());

  const host = prepareNativeHost({ outDir: out, runtimeDir, extensionId });
  let isolatedHostManifest = null;
  if (isolatedProfile) {
    const d = join(isolatedProfile, "NativeMessagingHosts");
    mkdirSync(d, { recursive: true });
    isolatedHostManifest = join(d, "dev.scout.spike_bridge.json");
    copyFileSync(host.manifestPath, isolatedHostManifest);
  }
  return {
    extensionId,
    extensionDir: ext,
    runtimeDir,
    wrapperPath: host.wrapperPath,
    hostManifestPath: host.manifestPath,
    installRealChrome: host.installPath,
    uninstallRealChrome: host.uninstallPath,
    isolatedHostManifest,
    echoServerCommand: `node ${JSON.stringify(join(BRIDGE, "echo-server.mjs"))} --runtime-dir ${JSON.stringify(runtimeDir)}`,
  };
}

if (isMain(import.meta.url)) {
  const arg = (name) => {
    const i = process.argv.indexOf(name);
    return i >= 0 ? process.argv[i + 1] : undefined;
  };
  const out = arg("--out");
  try {
    if (!out) throw new Error("usage: prepare.mjs --out <absolute dir> [--runtime-dir <dir>] [--isolated-profile <dir>]");
    const r = prepare({ out, runtimeDir: arg("--runtime-dir") ?? join(out, "runtime"), isolatedProfile: arg("--isolated-profile") ?? null });
    process.stdout.write(JSON.stringify(r, null, 2) + "\n");
  } catch (e) {
    process.stdout.write(JSON.stringify({ ok: false, error: e.message }) + "\n");
    process.exit(1);
  }
}
